// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCh0gujTRL5Dz-YHZ89JerP9o13Sb27i9A',
    appId: '1:926296751282:web:a32bb833b73a98fc195dab',
    messagingSenderId: '926296751282',
    projectId: 'howstories',
    authDomain: 'howstories.firebaseapp.com',
    storageBucket: 'howstories.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAxxBsZMLdnE66CbiCqgqXAxLLkF8gZ5XI',
    appId: '1:926296751282:android:b723aabe07f396d6195dab',
    messagingSenderId: '926296751282',
    projectId: 'howstories',
    storageBucket: 'howstories.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyA4T5Y6DhUwBId8q2lDa3B1Sjj4hiXMQ_0',
    appId: '1:926296751282:ios:be38d62306fb3161195dab',
    messagingSenderId: '926296751282',
    projectId: 'howstories',
    storageBucket: 'howstories.appspot.com',
    iosClientId: '926296751282-9vl6jlavd94dp2pgqe3aimit5c6lc4qu.apps.googleusercontent.com',
    iosBundleId: 'com.example.howStories',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyA4T5Y6DhUwBId8q2lDa3B1Sjj4hiXMQ_0',
    appId: '1:926296751282:ios:be38d62306fb3161195dab',
    messagingSenderId: '926296751282',
    projectId: 'howstories',
    storageBucket: 'howstories.appspot.com',
    iosClientId: '926296751282-9vl6jlavd94dp2pgqe3aimit5c6lc4qu.apps.googleusercontent.com',
    iosBundleId: 'com.example.howStories',
  );
}
